#@port = 8080
#@url = http://ab082f14dc7744a6b9ff129488fdacdd-201587194.us-east-1.elb.amazonaws.com/payments/
@url_payments = http://a376b39051ab44545898527550d36990-1129290018.us-east-1.elb.amazonaws.com/payments
@url = http://a376b39051ab44545898527550d36990-1129290018.us-east-1.elb.amazonaws.com/tastytap
#@url = http://127.0.0.1
#@base_url = /payments

GET {{url}}:/ping

###
GET http://{{url}}:8080/teste2/34663755553

###
POST http://{{url}}/product
Content-Type: application/json

{
  "name": "lanche1",
  "description": "descrição lanche1",
  "imageURL": "https://www.teste.com",
  "category": "SANDWICH",
  "price": 10.00
}

###

GET http://{{url}}/product/Sanduiche
Content-Type: application/json


###
POST http://{{url}}/user
Content-Type: application/json

{
  "cpf": "32621927831",
  "email": "thais@email.com",
  "name": "Thais"
}

###
POST http://{{url}}/order
Content-Type: application/json

{
  "cpf": "32621927831",
  "items": [
    {
      "productId": 1,
      "quantity": 1
    }
  ]
}

###
GET http://{{url}}/order

###
POST http://{{url}}//payment/webhook
Content-Type: application/json

{
  "transactionId": 34663983502,
  "status": "thais@email.com"
}


###
POST {{url_payments}}/create
Content-Type: application/json

{
  "referenceId": 123456767865,
  "amount": 10.00
}

###
GET {{url_payments}}/34663983502

###
POST http://{{url_payments}}/provider/webhook
Content-Type: application/json
Authorization: Bearer test-token

{
  "transactionId": 34663983502,
  "status": "APPROVED"
}

###
POST http://{{url_payments}}/mock/qrcode
Content-Type: application/json
Authorization: test_token

{
  "referenceId": 1234,
  "amount": 15.0
}
