apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: YWRtaW4=
  SPRING_DATASOURCE_PASSWORD: YWRtaW4=
  SPRING_DATASOURCE_URL: bW9uZ29kYitzcnY6Ly9hZG1pbjphZG1pbkBtb25nb2RiLXRhc3R5dGFwLWNsdXN0ZS50em1iNi5tb25nb2RiLm5ldC90YXN0eXRhcD9hdXRoU291cmNlPWFkbWluJnJldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhcHBOYW1lPW1vbmdvZGItdGFzdHl0YXAtY2x1c3Rlcg==